try {
    let result = 0 / 86;
} 
catch (error) {
    console.error("Error:", error.message);
}
